// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slepitlcsczbnecvnhgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZXBpdGxjc2N6Ym5lY3ZuaGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODM0MTQsImV4cCI6MjA2ODA1OTQxNH0.vMrcmOqNKWj_9RGIcNK4EiTBsgcsrOQfk0kvprG2Xt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});